export const StringConstant = {
  welcomeTitle: 'Discover Your',
  welcomeTitle2: 'Dream Job here',
  welcomeMessage:
    'Explore all the existing job roles based on your interest and study major',
  login: 'Login',
  register: 'Register',
  loginHere: 'Login here',
  welcomeBackMsg: "Welcome back you've been missed!",
  email: 'Email',
  password: 'Password',
  forgot: 'Forgot your password?',
  signIn: 'Sign in',
  create: 'Create new account',
  orContinueWith: 'Or continue with',
  createAccount: 'Create Account',
  createAccountMsg:
    'Create an account so you can explore all the existing jobs',
  confirmPass: 'Confirm Password',
  signUp: 'Sign up',
  alreadyHaveAcc: 'Already have an account',
  validEmail: 'Please provide valid email',
  validPass: 'Password cannot be less 8 characters',
  validConfirmPass: 'Password does not match',
};
